[versions]
agp = "8.8.0"
kotlin = "2.1.10"
coreKtx = "1.15.0"
junit = "5.10.0"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.0"
composeBom = "2024.04.01"
jetbrainsKotlinJvm = "2.0.0"
publishing = "1.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "publishing" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
